global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'observability-cluster'
    environment: 'docker'

rule_files:
  - "/etc/prometheus/alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'ai-anomaly-detection'
    static_configs:
      - targets: ['ai-anomaly-detection:8083']
    metrics_path: '/metrics'
    scrape_interval: 5s
